name: Foil Stamping in NYC
favicon: null
layout_spectrum: 0.23569791624322534
typography_spectrum: 0.7836492015048862
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6223102025687695
  lightness: 0.4916821711231023
  saturation: 0.43569045956246555
  rhythmicContrast: 0.3945500343106687
purpose: []
